spring.application.name=medprep-backend

server.port=8080

# ==========================================================
# PostgreSQL
# ==========================================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/medprep}
spring.datasource.username=${DB_USERNAME:mary}
spring.datasource.password=${DB_PASSWORD:}

# ==========================================================
# JPA / Hibernate
# ==========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================================
# JWT
# ==========================================================

app.jwt.secret=${JWT_SECRET:medprep-development-secret-key-change-this-very-long-value}
app.jwt.expiration-ms=86400000

# ==========================================================
# Gemini
# ==========================================================

gemini.api-key=${GEMINI_API_KEY:}
gemini.model=gemini-3.6-flash
